name       : pragha
version    : 1.3.99.1
release    : 1
source     :
    - https://github.com/pragha-music-player/pragha/releases/download/v1.3.99.1/pragha-1.3.99.1.tar.bz2 : dca23b8e09a16c6e45e6edc245fbd8d731f9353adafb2fe035adbb486e23970d
license    : GPL-3.0-or-later
summary    : Lightweight Music Player for GNU/Linux
component  : multimedia.audio
description: |
    Pragha is a Lightweight Music Player for GNU/Linux, based on Gtk and sqlite. It is completely written in C, constructed to be fast, light, and simultaneously tries to be complete without obstructing the daily work. ;)
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib_c)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(totem-plparser)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libmtp)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rygel-server-2.6)
    - pkgconfig(grilo-0.3)
    - pkgconfig(grilo-net-0.3)
    - pkgconfig(libcdio)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libcddb)
    - pkgconfig(libxfce4util-1.0)
    - pkgconfig(gupnp-1.2)
    - xfce4-dev-tools-devel
setup      : |
    %patch -p1 < $pkgfiles/gupnp.patch
    %reconfigure
    %configure
build      : |
    %make
install    : |
    %make_install
